export const DEFAULT_GLOSSARY: { abbreviation: string; description: string }[] = [
  { abbreviation: "K", description: "Knit" },
  { abbreviation: "P", description: "Purl" },
  { abbreviation: "CO", description: "Cast On" },
  { abbreviation: "BO", description: "Bind Off / Cast Off" },
  { abbreviation: "St(s)", description: "Stitch(es)" },
  { abbreviation: "RS", description: "Right Side" },
  { abbreviation: "WS", description: "Wrong Side" },
  { abbreviation: "K2tog", description: "Knit 2 Together (right-leaning decrease)" },
  { abbreviation: "SSK", description: "Slip, Slip, Knit (left-leaning decrease)" },
  { abbreviation: "YO", description: "Yarn Over" },
  { abbreviation: "Sl", description: "Slip stitch" },
  { abbreviation: "PM", description: "Place Marker" },
  { abbreviation: "SM", description: "Slip Marker" },
  { abbreviation: "Rep", description: "Repeat" },
  { abbreviation: "Inc", description: "Increase" },
  { abbreviation: "Dec", description: "Decrease" },
  { abbreviation: "M1", description: "Make 1 (increase)" },
  { abbreviation: "M1L", description: "Make 1 Left" },
  { abbreviation: "M1R", description: "Make 1 Right" },
  { abbreviation: "KFB", description: "Knit Front and Back (increase)" },
  { abbreviation: "PFB", description: "Purl Front and Back (increase)" },
  { abbreviation: "Tbl", description: "Through Back Loop" },
  { abbreviation: "Wyif", description: "With Yarn in Front" },
  { abbreviation: "Wyib", description: "With Yarn in Back" },
  { abbreviation: "DPN", description: "Double-Pointed Needle(s)" },
  { abbreviation: "Cn", description: "Cable Needle" },
  { abbreviation: "C4F", description: "Cable 4 Front" },
  { abbreviation: "C4B", description: "Cable 4 Back" },
  { abbreviation: "Sk", description: "Skip" },
  { abbreviation: "Rem", description: "Remaining" },
  { abbreviation: "Alt", description: "Alternate" },
  { abbreviation: "Beg", description: "Beginning" },
  { abbreviation: "Cont", description: "Continue" },
  { abbreviation: "Tog", description: "Together" },
  { abbreviation: "Rnd", description: "Round" },
  { abbreviation: "MC", description: "Main Color" },
  { abbreviation: "CC", description: "Contrast Color" },
  { abbreviation: "Sk2p", description: "Slip 1, Knit 2 Together, Pass Slipped Stitch Over" },
  { abbreviation: "Psso", description: "Pass Slipped Stitch Over" },
  { abbreviation: "Patt", description: "Pattern" },
];
